name=PUSPINORFlash
version=0.1.2
author=Santi24Yt
maintainer=Santi24Yt
sentence=An arduino library for sectored NOR SPI Flash Memory that wrapps SPIMemory
paragraph=Wrapper of SPIMemory for easier usage of sectored NOR memory
category=Device Control
url=https://github.com/Propulsion-UNAM/PUSPINORFlash
architectures=arduino-pico,rp2040
includes=PUSPINORFlash.h
depends=SPIMemory (>=3.4.2)